version: '3.8'
services:
  postgres:
    restart: always
    container_name: postgres
    image: postgres:13.3
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "rush"
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"